### ISSUE TITLE
Minor issues with glossary responses

### ISSUE THREAD

**Issue by beechnut** [18F/charlie#350]
## Background Information

1) Charlie [isn't defining T&M](https://gsa-tts.slack.com/archives/C028GH7FA/p1631809736007000?thread_ts=1631809647.006100&cid=C028GH7FA
) despite [T&M being an entry in the procurement glossary](https://github.com/18F/procurement-glossary/blob/master/abbreviations.yml#L1741).

2) When there's no longform of an acronym, the response has `null` where the term should be:

![Screen Shot 2021-09-16 at 12 35 24 PM](https://user-images.githubusercontent.com/1887182/133651275-ba4cd85e-e557-449a-a2f0-db73373ec1ab.png)

## Implementation Steps

- [ ] Debug script to determine why T&M isn't getting caught in the lookup

## Acceptance Criteria

- [ ] Charlie returns a response to `@Charlie define T&M`.
- [ ] Charlie's response to `1102` looks like "The term **1102** means Federal Government job series number for procurement personnel"
